apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: web-app
  labels:
    app: employees
spec:
  containers:
  - name: web-app-container
    image: 808973727775.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment:webapp-v0.1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "10.96.191.118"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: pwd
    - name: DATABASE
      value: employees
    - name: APP_COLOR
      value: lime
    - name: DBPORT
      value: "3306"
  imagePullSecrets:
  - name: ecr-registry-secret

